python preprocessing.py --folderpath newlabeledstatusfiles/ --start 1 --end 30
python preprocessing.py --folderpath newlabeledstatusfiles/ --start 31 --end 60
python preprocessing.py --folderpath newlabeledstatusfiles/ --start 61 --end 90
python preprocessing.py --folderpath newlabeledstatusfiles/ --start 91 --end 120
python preprocessing.py --folderpath newlabeledstatusfiles/ --start 121 --end 150
python preprocessing.py --folderpath newlabeledstatusfiles/ --start 151 --end 180
python preprocessing.py --folderpath newlabeledstatusfiles/ --start 181 --end 210
python preprocessing.py --folderpath newlabeledstatusfiles/ --start 211 --end 240
python preprocessing.py --folderpath newlabeledstatusfiles/ --start 241 --end 270
python preprocessing.py --folderpath newlabeledstatusfiles/ --start 271 --end 300
python preprocessing.py --folderpath newlabeledstatusfiles/ --start 301 --end 330
python preprocessing.py --folderpath newlabeledstatusfiles/ --start 331 --end 360
python preprocessing.py --folderpath newlabeledstatusfiles/ --start 361 --end 390
python preprocessing.py --folderpath newlabeledstatusfiles/ --start 391 --end 420
python preprocessing.py --folderpath newlabeledstatusfiles/ --start 421 --end 450
python preprocessing.py --folderpath newlabeledstatusfiles/ --start 451 --end 480
python preprocessing.py --folderpath newlabeledstatusfiles/ --start 481 --end 510
python preprocessing.py --folderpath newlabeledstatusfiles/ --start 511 --end 540
python preprocessing.py --folderpath newlabeledstatusfiles/ --start 541 --end 570
python preprocessing.py --folderpath newlabeledstatusfiles/ --start 571 --end 600
python preprocessing.py --folderpath newlabeledstatusfiles/ --start 601 --end 630
python preprocessing.py --folderpath newlabeledstatusfiles/ --start 631 --end 660
python preprocessing.py --folderpath newlabeledstatusfiles/ --start 661 --end 690
python preprocessing.py --folderpath newlabeledstatusfiles/ --start 691 --end 700
