python preprocessing_formatting.py --folderpath newlabeledstatusfiles/ --start 1 --end 30 --outputfolder ./
python preprocessing_formatting.py --folderpath newlabeledstatusfiles/ --start 31 --end 60 --outputfolder ./
python preprocessing_formatting.py --folderpath newlabeledstatusfiles/ --start 61 --end 90 --outputfolder ./
python preprocessing_formatting.py --folderpath newlabeledstatusfiles/ --start 91 --end 120 --outputfolder ./
python preprocessing_formatting.py --folderpath newlabeledstatusfiles/ --start 121 --end 150 --outputfolder ./
python preprocessing_formatting.py --folderpath newlabeledstatusfiles/ --start 151 --end 180 --outputfolder ./
python preprocessing_formatting.py --folderpath newlabeledstatusfiles/ --start 181 --end 210 --outputfolder ./
python preprocessing_formatting.py --folderpath newlabeledstatusfiles/ --start 211 --end 240 --outputfolder ./
python preprocessing_formatting.py --folderpath newlabeledstatusfiles/ --start 241 --end 270 --outputfolder ./
python preprocessing_formatting.py --folderpath newlabeledstatusfiles/ --start 271 --end 300 --outputfolder ./
python preprocessing_formatting.py --folderpath newlabeledstatusfiles/ --start 301 --end 330 --outputfolder ./
python preprocessing_formatting.py --folderpath newlabeledstatusfiles/ --start 331 --end 360 --outputfolder ./
python preprocessing_formatting.py --folderpath newlabeledstatusfiles/ --start 361 --end 390 --outputfolder ./
python preprocessing_formatting.py --folderpath newlabeledstatusfiles/ --start 391 --end 420 --outputfolder ./
python preprocessing_formatting.py --folderpath newlabeledstatusfiles/ --start 421 --end 450 --outputfolder ./
python preprocessing_formatting.py --folderpath newlabeledstatusfiles/ --start 451 --end 480 --outputfolder ./
python preprocessing_formatting.py --folderpath newlabeledstatusfiles/ --start 481 --end 510 --outputfolder ./
python preprocessing_formatting.py --folderpath newlabeledstatusfiles/ --start 511 --end 540 --outputfolder ./
python preprocessing_formatting.py --folderpath newlabeledstatusfiles/ --start 541 --end 570 --outputfolder ./
python preprocessing_formatting.py --folderpath newlabeledstatusfiles/ --start 571 --end 600 --outputfolder ./
python preprocessing_formatting.py --folderpath newlabeledstatusfiles/ --start 601 --end 630 --outputfolder ./
python preprocessing_formatting.py --folderpath newlabeledstatusfiles/ --start 631 --end 660 --outputfolder ./
python preprocessing_formatting.py --folderpath newlabeledstatusfiles/ --start 661 --end 690 --outputfolder ./
python preprocessing_formatting.py --folderpath newlabeledstatusfiles/ --start 691 --end 700 --outputfolder ./
